name: Image push release
on:
  push:
    tags:
      - v*
jobs:
  push-image:
    name: Image build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ steps.repo_name.outputs.repository }}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false

      - name: Discover CNI plugins version
        run: |
          echo "CNI_VERSION=$(echo ${{ github.ref_name }} | awk '{gsub(/-update.*$/,"")}1')" >> $GITHUB_ENV

      - name: Validate CNI version
        run: |
          if [[ "${{ env.CNI_VERSION }}" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)?$ ]]; then
            echo "Valid CNI Version"
          else
            echo "Invalid CNI version/tag provided"
            exit 1
          fi
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.CNI_VERSION }}
          tags: |
            ghcr.io/k8snetworkplumbingwg/plugins:${{ github.ref_name }}
          file: ./Dockerfile
